version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/azure-sql-edge
    container_name: sqlserver
    environment:
      SA_PASSWORD: QLTV@1234
      ACCEPT_EULA: Y
    ports:
      - "1433:1433"

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - "8080:8080"
    depends_on:
      - sqlserver

volumes:
  sqlserver-data:
  sqlserver-backup: